language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/NathanReb/ocaml-ci-scripts/check-formatting/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=fiat-p256
    - DISTRO=alpine-3.7
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - HUB_USER=nathanreb OCAMLFORMAT=0.9
